"""Pydantic schemas package."""

# Base schemas
from .base import (
    BaseSchema,
    TimestampSchema,
    UUIDSchema,
    PaginatedResponse,
    PaginationParams,
    ErrorResponse
)

# User schemas
from .user import (
    UserRegistration,
    UserLogin,
    PasswordReset,
    PasswordResetConfirm,
    OAuthLogin,
    UserProfileUpdate,
    UserProfile,
    User,
    UserWithProfile,
    AuthToken,
    AuthResponse,
    UserOAuthIdentity,
    UserOAuthIdentityCreate
)

# Subscription schemas
from .subscription import (
    Plan,
    PlanCreate,
    PlanUpdate,
    SubscriptionCreate,
    SubscriptionUpdate,
    Subscription,
    SubscriptionWithUsage,
    UsageQuota,
    BillingInfo,
    Invoice,
    PlanComparison,
    SubscriptionAnalytics
)

# Stock schemas
from .stock import (
    StockBase,
    StockCreate,
    StockUpdate,
    Stock,
    StockSearchQuery,
    StockSearchResult,
    PriceDataBase,
    PriceDataCreate,
    PriceData,
    StockDailyMetricsBase,
    StockDailyMetricsCreate,
    StockDailyMetrics,
    MarketIndex,
    HotStock,
    HotStocksResponse,
    StockDetail,
    PriceHistoryQuery,
    PriceHistoryResponse,
    TechnicalIndicators,
    PaginatedStocksResponse,
    PaginatedPriceDataResponse
)

# Financial schemas
from .financial import (
    FinancialReportBase,
    FinancialReportCreate,
    FinancialReport,
    EarningsBase,
    EarningsCreate,
    Earnings,
    BalanceSheetBase,
    BalanceSheetCreate,
    BalanceSheet,
    IncomeStatementBase,
    IncomeStatementCreate,
    IncomeStatement,
    CashFlowBase,
    CashFlowCreate,
    CashFlow,
    FinancialRatiosBase,
    FinancialRatiosCreate,
    FinancialRatios,
    FinancialSummary,
    EarningsCalendarEntry,
    EarningsCalendarResponse,
    PaginatedFinancialReportsResponse,
    PaginatedEarningsResponse,
    PaginatedBalanceSheetsResponse,
    PaginatedIncomeStatementsResponse,
    PaginatedCashFlowsResponse
)

# AI Analysis schemas
from .ai_analysis import (
    AIAnalysisRequest,
    BulkAnalysisRequest,
    AIAnalysisBase,
    AIAnalysisCreate,
    AIAnalysis,
    FundamentalAnalysisResult,
    TechnicalAnalysisResult,
    SentimentAnalysisResult,
    RiskAssessmentResult,
    PricePredictionResult,
    AnalysisHistory,
    AnalysisQueueStatus,
    AnalysisComparison,
    AnalysisExportRequest,
    AnalysisExportResponse,
    PaginatedAIAnalysisResponse,
    AnalysisStatistics
)

# Watchlist schemas
from .watchlist import (
    WatchlistBase,
    WatchlistCreate,
    WatchlistUpdate,
    Watchlist,
    WatchlistWithStocks,
    WatchlistStockBase,
    WatchlistStockCreate,
    WatchlistStockUpdate,
    WatchlistStock,
    WatchlistStockWithPrice,
    WatchlistAlertBase,
    WatchlistAlertCreate,
    WatchlistAlert,
    WatchlistPerformance,
    WatchlistStatistics,
    PublicWatchlistSummary,
    WatchlistFollower,
    WatchlistImportRequest,
    WatchlistExportRequest,
    WatchlistExportResponse,
    BulkWatchlistStockOperation,
    BulkOperationResult,
    PaginatedWatchlistsResponse,
    PaginatedWatchlistStocksResponse,
    PaginatedWatchlistAlertsResponse,
    PaginatedPublicWatchlistsResponse
)

# Notification schemas
from .notification import (
    NotificationBase,
    NotificationCreate,
    NotificationUpdate,
    Notification,
    NotificationPreferencesBase,
    NotificationPreferencesCreate,
    NotificationPreferencesUpdate,
    NotificationPreferences,
    NotificationTemplateBase,
    NotificationTemplateCreate,
    NotificationTemplateUpdate,
    NotificationTemplate,
    NotificationChannelBase,
    NotificationChannelCreate,
    NotificationChannelUpdate,
    NotificationChannel,
    NotificationDeliveryBase,
    NotificationDeliveryCreate,
    NotificationDelivery,
    NotificationStatistics,
    BulkNotificationRequest,
    BulkNotificationResult,
    NotificationDigest,
    PaginatedNotificationsResponse,
    PaginatedNotificationTemplatesResponse,
    PaginatedNotificationChannelsResponse
)

# API Response schemas
from .api_response import (
    APIResponse,
    ErrorDetail,
    APIErrorResponse,
    SuccessResponse,
    CreatedResponse,
    UpdatedResponse,
    DeletedResponse,
    PaginationMeta,
    PaginatedResponse,
    ValidationErrorResponse,
    AuthenticationErrorResponse,
    AuthorizationErrorResponse,
    RateLimitErrorResponse,
    HealthCheckResponse,
    BatchOperationResult,
    BatchResponse,
    FileUploadResponse,
    ExportResponse,
    SearchMeta,
    SearchResponse,
    AnalyticsResponse,
    WebSocketMessage,
    WebSocketErrorMessage,
    StatusResponse
)

__all__ = [
    # Base
    "BaseSchema",
    "TimestampSchema", 
    "UUIDSchema",
    "PaginatedResponse",
    "PaginationParams",
    "ErrorResponse",
    
    # User
    "UserRegistration",
    "UserLogin",
    "PasswordReset",
    "PasswordResetConfirm",
    "OAuthLogin",
    "UserProfileUpdate",
    "UserProfile",
    "User",
    "UserWithProfile",
    "AuthToken",
    "AuthResponse",
    "UserOAuthIdentity",
    "UserOAuthIdentityCreate",
    
    # Subscription
    "Plan",
    "PlanCreate",
    "PlanUpdate",
    "SubscriptionCreate",
    "SubscriptionUpdate",
    "Subscription",
    "SubscriptionWithUsage",
    "UsageQuota",
    "BillingInfo",
    "Invoice",
    "PlanComparison",
    "SubscriptionAnalytics",
    
    # Stock
    "StockBase",
    "StockCreate",
    "StockUpdate",
    "Stock",
    "StockSearchQuery",
    "StockSearchResult",
    "PriceDataBase",
    "PriceDataCreate",
    "PriceData",
    "StockDailyMetricsBase",
    "StockDailyMetricsCreate",
    "StockDailyMetrics",
    "MarketIndex",
    "HotStock",
    "HotStocksResponse",
    "StockDetail",
    "PriceHistoryQuery",
    "PriceHistoryResponse",
    "TechnicalIndicators",
    "PaginatedStocksResponse",
    "PaginatedPriceDataResponse",
    
    # Financial
    "FinancialReportBase",
    "FinancialReportCreate",
    "FinancialReport",
    "EarningsBase",
    "EarningsCreate",
    "Earnings",
    "BalanceSheetBase",
    "BalanceSheetCreate",
    "BalanceSheet",
    "IncomeStatementBase",
    "IncomeStatementCreate",
    "IncomeStatement",
    "CashFlowBase",
    "CashFlowCreate",
    "CashFlow",
    "FinancialRatiosBase",
    "FinancialRatiosCreate",
    "FinancialRatios",
    "FinancialSummary",
    "EarningsCalendarEntry",
    "EarningsCalendarResponse",
    "PaginatedFinancialReportsResponse",
    "PaginatedEarningsResponse",
    "PaginatedBalanceSheetsResponse",
    "PaginatedIncomeStatementsResponse",
    "PaginatedCashFlowsResponse",
    
    # AI Analysis
    "AIAnalysisRequest",
    "BulkAnalysisRequest",
    "AIAnalysisBase",
    "AIAnalysisCreate",
    "AIAnalysis",
    "FundamentalAnalysisResult",
    "TechnicalAnalysisResult",
    "SentimentAnalysisResult",
    "RiskAssessmentResult",
    "PricePredictionResult",
    "AnalysisHistory",
    "AnalysisQueueStatus",
    "AnalysisComparison",
    "AnalysisExportRequest",
    "AnalysisExportResponse",
    "PaginatedAIAnalysisResponse",
    "AnalysisStatistics",
    
    # Watchlist
    "WatchlistBase",
    "WatchlistCreate",
    "WatchlistUpdate",
    "Watchlist",
    "WatchlistWithStocks",
    "WatchlistStockBase",
    "WatchlistStockCreate",
    "WatchlistStockUpdate",
    "WatchlistStock",
    "WatchlistStockWithPrice",
    "WatchlistAlertBase",
    "WatchlistAlertCreate",
    "WatchlistAlert",
    "WatchlistPerformance",
    "WatchlistStatistics",
    "PublicWatchlistSummary",
    "WatchlistFollower",
    "WatchlistImportRequest",
    "WatchlistExportRequest",
    "WatchlistExportResponse",
    "BulkWatchlistStockOperation",
    "BulkOperationResult",
    "PaginatedWatchlistsResponse",
    "PaginatedWatchlistStocksResponse",
    "PaginatedWatchlistAlertsResponse",
    "PaginatedPublicWatchlistsResponse",
    
    # Notification
    "NotificationBase",
    "NotificationCreate",
    "NotificationUpdate",
    "Notification",
    "NotificationPreferencesBase",
    "NotificationPreferencesCreate",
    "NotificationPreferencesUpdate",
    "NotificationPreferences",
    "NotificationTemplateBase",
    "NotificationTemplateCreate",
    "NotificationTemplateUpdate",
    "NotificationTemplate",
    "NotificationChannelBase",
    "NotificationChannelCreate",
    "NotificationChannelUpdate",
    "NotificationChannel",
    "NotificationDeliveryBase",
    "NotificationDeliveryCreate",
    "NotificationDelivery",
    "NotificationStatistics",
    "BulkNotificationRequest",
    "BulkNotificationResult",
    "NotificationDigest",
    "PaginatedNotificationsResponse",
    "PaginatedNotificationTemplatesResponse",
    "PaginatedNotificationChannelsResponse",
    
    # API Response
    "APIResponse",
    "ErrorDetail",
    "APIErrorResponse",
    "SuccessResponse",
    "CreatedResponse",
    "UpdatedResponse",
    "DeletedResponse",
    "PaginationMeta",
    "PaginatedResponse",
    "ValidationErrorResponse",
    "AuthenticationErrorResponse",
    "AuthorizationErrorResponse",
    "RateLimitErrorResponse",
    "HealthCheckResponse",
    "BatchOperationResult",
    "BatchResponse",
    "FileUploadResponse",
    "ExportResponse",
    "SearchMeta",
    "SearchResponse",
    "AnalyticsResponse",
    "WebSocketMessage",
    "WebSocketErrorMessage",
    "StatusResponse",
]