name: Basic Validation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # Basic validation that should always pass
  basic-checks:
    name: Basic Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check repository structure
      run: |
        echo "🔍 Checking repository structure..."
        
        # Check for basic directories
        if [ -d "backend" ]; then
          echo "✅ Backend directory found"
        else
          echo "⚠️ Backend directory not found"
        fi
        
        if [ -d "frontend" ]; then
          echo "✅ Frontend directory found"
        else
          echo "⚠️ Frontend directory not found"
        fi
        
        # Check for key files
        if [ -f "README.md" ]; then
          echo "✅ README.md found"
        else
          echo "⚠️ README.md not found"
        fi
        
        if [ -f "backend/requirements.txt" ]; then
          echo "✅ Backend requirements.txt found"
        else
          echo "⚠️ Backend requirements.txt not found"
        fi
        
        if [ -f "frontend/package.json" ]; then
          echo "✅ Frontend package.json found"
        else
          echo "⚠️ Frontend package.json not found"
        fi

    - name: Check Python syntax (if backend exists)
      if: hashFiles('backend/**/*.py') != ''
      run: |
        echo "🐍 Checking Python syntax..."
        python -m py_compile backend/**/*.py || echo "⚠️ Python syntax issues found"

    - name: Check JSON files
      run: |
        echo "📄 Checking JSON files..."
        for file in $(find . -name "*.json" -not -path "./node_modules/*" -not -path "./.git/*"); do
          if python -m json.tool "$file" > /dev/null 2>&1; then
            echo "✅ $file is valid JSON"
          else
            echo "❌ $file has invalid JSON syntax"
          fi
        done

    - name: Check for common issues
      run: |
        echo "🔍 Checking for common issues..."
        
        # Check for large files
        large_files=$(find . -type f -size +10M -not -path "./.git/*" -not -path "./node_modules/*" 2>/dev/null || true)
        if [ -n "$large_files" ]; then
          echo "⚠️ Large files found:"
          echo "$large_files"
        else
          echo "✅ No large files found"
        fi
        
        # Check for secrets patterns
        if grep -r "password\|secret\|key" --include="*.py" --include="*.js" --include="*.ts" --exclude-dir=node_modules --exclude-dir=.git . | grep -v "# " | head -5; then
          echo "⚠️ Potential secrets found (review manually)"
        else
          echo "✅ No obvious secrets found"
        fi

    - name: Summary
      run: |
        echo "📋 Basic validation completed"
        echo "This workflow performs basic repository health checks"
        echo "For detailed testing, check the main CI workflow"

  # Test basic Python setup (if backend exists)
  python-basic:
    name: Python Basic Setup
    runs-on: ubuntu-latest
    if: hashFiles('backend/**/*.py') != ''

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Test Python installation
      run: |
        python --version
        pip --version
        echo "✅ Python setup successful"

    - name: Install basic dependencies
      working-directory: ./backend
      run: |
        if [ -f "requirements.txt" ]; then
          echo "📦 Installing from requirements.txt..."
          pip install -r requirements.txt || echo "⚠️ Some dependencies failed to install"
        else
          echo "⚠️ No requirements.txt found, installing basic packages"
          pip install fastapi uvicorn pytest
        fi

    - name: Test Python imports
      working-directory: ./backend
      run: |
        echo "🧪 Testing Python imports..."
        python -c "import sys; print('Python path:', sys.path)" || true
        if [ -d "app" ]; then
          python -c "import app" || echo "⚠️ Could not import app module"
        fi

  # Test basic Node.js setup (if frontend exists)
  nodejs-basic:
    name: Node.js Basic Setup
    runs-on: ubuntu-latest
    if: hashFiles('frontend/package.json') != ''

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Test Node.js installation
      run: |
        node --version
        npm --version
        echo "✅ Node.js setup successful"

    - name: Install dependencies
      working-directory: ./frontend
      run: |
        if [ -f "package-lock.json" ]; then
          echo "📦 Installing with npm ci..."
          npm ci || echo "⚠️ npm ci failed, trying npm install"
          npm install || echo "⚠️ npm install also failed"
        elif [ -f "package.json" ]; then
          echo "📦 Installing with npm install..."
          npm install || echo "⚠️ npm install failed"
        else
          echo "❌ No package.json found"
          exit 1
        fi

    - name: Test basic scripts
      working-directory: ./frontend
      run: |
        echo "🧪 Testing available npm scripts..."
        npm run --silent 2>/dev/null || echo "⚠️ Could not list npm scripts"
        
        # Try to run basic commands
        if npm run build --if-present; then
          echo "✅ Build script works"
        else
          echo "⚠️ Build script failed or not available"
        fi